server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**

        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/v1/category/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/book/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**

        - id: cart-item-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart-item/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**

        - id: order-item-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order-item/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true