server:
  port: 0

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ftDB

logging:
  level:
    org.springframework: INFO

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true